CREATE DATABASE IF NOT EXISTS TvSat;

USE TvSat;

CREATE TABLE IF NOT EXISTS satellite(
id INT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
launch_date date NOT NULL,
launch_rkt VARCHAR(255) NOT NULL,
region VARCHAR(255) NOT NULL,
pos VARCHAR(8) NOT NULL,
EIRP VARCHAR(6),
sys VARCHAR(20) NOT NULL, 
beam VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS channels(
id int PRIMARY KEY,
name VARCHAR(255) NOT NULL,
encryption VARCHAR(255),
vid_encode VARCHAR(255) NOT NULL,
FEC VARCHAR(255) NOT NULL,
SR int NOT NULL
);

CREATE TABLE IF NOT EXISTS chan_lang(
id INT NOT NULL, 
lang VARCHAR(255) NOT NULL,
CONSTRAINT PK PRIMARY KEY (id, lang)
);

CREATE TABLE IF NOT EXISTS chan_sat(
channel_id INT NOT NULL,
sat_id INT NOT NULL,
prov_pack VARCHAR(255),
frequency VARCHAR(255) NOT NULL,
CONSTRAINT PK PRIMARY KEY (channel_id, sat_id, frequency)
);

CREATE TABLE IF NOT EXISTS user(
username VARCHAR(255) PRIMARY KEY,
pass VARCHAR(255) NOT NULL
email VARCHAR(255) UNIQUE NOT NULL,
region VARCHAR(255) NOT NULL,
location VARCHAR(255) NOT NULL,
birthdate DATE NOT NULL,
gender VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS fave_channel(
username VARCHAR(255) NOT NULL,
channel_name VARCHAR(255) NOT NULL,
CONSTRAINT PK PRIMARY KEY (username, channel_name)
);

